project:
  type: website
  output-dir: website
  preview:
    port: 7777
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
website:
  title: "Marie bekommt weniger Pension als Otto"
  favicon: img/favicon-wifo.ico
  search: false
  navbar: false
format:
  html:
    theme: [cosmo, style/styles.scss]
    grid:
      # sidebar-width: 300px
      body-width: 826px
      margin-width: 380px
      gutter-width: 8px 
    toc: false
    page-layout: article
    fontsize: 15px