project:
  type: website
  output-dir: website
  preview:
    port: 7777
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
website:
  title: "AK-OOe-Pensionen"
  favicon: img/ak-logo.svg
  search: false
  # page-footer: |
  #     [![](img/logo.svg){height=30px}](https://www.wifo.ac.at/) <br><br>
  #     © 2024 — AK OBERÖSTERREICH | WIFO — <a href="mailto:data.science@wifo.ac.at">data.science@wifo.ac.at</a>
  # navbar: # just comment out to remove
  #   title: | 
  #     [![](img/ak-logo.svg){height="70px"}](/) &nbsp;
  #   left: 
  #     - index.qmd
  #   tools:
  #     - icon: github
  #       href: https://github.com/schmoigl
format:
  html:
    theme: [cosmo, style/styles.scss]
    # css: style/styles.css # works only with simple .css not .scss
    toc: false
    page-layout: article
    fontsize: 15px