project:
  type: website
  output-dir: website
  preview:
    port: 7777
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
    - households.qmd
website:
  title: "AK-Pensionsreformrechner "
  favicon: img/favicon.ico
  search: false
  page-footer: |
    <div style="display: flex; justify-content: center; align-items: center;">
      <a href="https://ooe.arbeiterkammer.at/index.html">
        <img src="img/ak-logo.svg" height="64px" alt="AK Logo">
      </a>
      <a href="https://www.wifo.ac.at/">
        <img src="img/WIFO_kurz_rechts.svg" height="28px" alt="WIFO Logo">
      </a>
    </div>
    <br>
    © 2024 AK Oberösterreich | Volksgartenstrasse 40 4020 Linz, +43 50 6906 0
  navbar: 
    title: | 
      [![](img/ak-logo.svg){height="70px"}](https://ooe.arbeiterkammer.at/index.html) &nbsp;
    left: 
      - index.qmd
format:
  html:
    theme: [cosmo, style/styles.scss]
    grid:
      # sidebar-width: 300px
      body-width: 826px
      # margin-width: 360px
      gutter-width: 0px
    toc: false
    page-layout: article
    fontsize: 15px